### ISSUE TITLE
Any plan on implementation with Python?

### ISSUE THREAD

**Issue by YuhuaBillChen** [ai-med/QuickNATv2#1]
Hi,

You guys really did a fantastic job here! Very nice results.

However, you guys are using Matlab based software, which sadly we don't have one on our workstation. I wonder as most of the society in deep learning are using Python package (Tensorflow, PyTorch, Caffe2 etc.), are you guys planning to release a python version of it?

Thanks,
Bill

**Comment by abhi4ssj** [comment]
Hi Yuhua,

We are currently working on a Tensorflow and PyTorch implementation. Planning to release it soon. 
We are also planning to host a web based service to improve usability. If all goes well, it should be up in 1-2 months. I'll update it here.

Thanks,
Abhijit
