### ISSUE TITLE
error when run RunFile.m

### ISSUE THREAD

**Issue by idhamari** [ai-med/QuickNATv2#4]
Undefined function or variable 'MRIread'.

Error in RunFile (line 14)
DataVol = MRIread([DataPath,FileName]);

**Comment by idhamari** [comment]
After reading the whole document I found out how to do it. It is better to put points 5 and 6 before 4 to avoid confusion.

**Comment by idhamari** [comment]
Another error:
Undefined function or variable 'ReMapSagProbMap'.

**Comment by abhi4ssj** [comment]
The function 'ReMapSagProbMap' is inside the folder QuickNAT_Networks/..
Add all the files in the folder to the Matlab Path and run the code.

**Comment by idhamari** [comment]
Thanks for the info. I think it is better to add this line to your SegmentVol.m

addpath('../QuickNAT_Networks')

**Comment by abhi4ssj** [comment]
Thanks for the feedback. I added it.

**Comment by Zhenya97** [comment]
> Undefined function or variable 'MRIread'.
> Error in RunFile (line 14)
> DataVol = MRIread([DataPath,FileName]);

Can you plz give more explanation about how to solve this problem? Thanks.
